/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyek;

import database.database;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.table.TableModel;
import javax.swing.JFileChooser;

/**
 *
 * @author dell
 */
public class datapetugas extends javax.swing.JFrame {
    private Connection koneksi;
    private Statement st;
    JFileChooser jfc;
    File file;
    /**
     * Creates new form produk
     */
    public datapetugas() {
        initComponents();
    }
    
    
    
    public void Buatlagi(){
       String id = txtid.getText();
       String nama = txtnama.getText();
       String alamat = txtalamat.getText();
       String email = txtemail.getText();
       String password = txtpass.getText();
       String nohp = txtnohp.getText();
       String image = txtfoto.getText();
       image = image.replace("\\","\\\\");
        try{
        Statement state  = database.GetConnection().createStatement();
        state.executeUpdate("insert into data_petugas values ('"+id+"','"+nama+"','"+alamat+"','"+email+"','"+password+"','"+nohp+"','"+image+"',NOW())");
        JOptionPane.showMessageDialog(this, "Data Berhasil Dibuat !");
        try { 
        }catch (Exception e) {
        }
        
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, "Silahkan Cek Ulang!");
        }
    }
    
    public void editdata(){
       String id = txtid.getText();
       String nama = txtnama.getText();
       String alamat = txtalamat.getText();
       String email = txtemail.getText();
       String password = txtpass.getText();
       String nohp = txtnohp.getText();
       String image = txtfoto.getText();
       image = image.replace("\\","\\\\");
        try{
        Statement state  = database.GetConnection().createStatement();
        state.executeUpdate("update data_petugas set foto='"+image+"', username='"+email+"', nama='"+nama+"', alamat='"+alamat+"', pass='"+password+"', no_hp='"+nohp+"' where id='"+id+"';");
        JOptionPane.showMessageDialog(this, "Data Berhasil DiUpdate !");
         
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, "Gak Bisa Bro!");
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        refreshminum = new javax.swing.JButton();
        txtid = new javax.swing.JTextField();
        tmbhminum = new javax.swing.JButton();
        txtnohp = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelminum = new javax.swing.JTable();
        editminum = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        dataminuman = new javax.swing.JButton();
        txtemail = new javax.swing.JTextField();
        hapusminum = new javax.swing.JButton();
        kembali = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtfoto = new javax.swing.JTextField();
        btncari = new javax.swing.JButton();
        labelfoto = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtpass = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtalamat = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        txtnama = new javax.swing.JTextField();
        btnget = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 255));

        jPanel1.setBackground(new java.awt.Color(0, 0, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(1920, 1080));
        jPanel1.setMinimumSize(new java.awt.Dimension(1920, 1080));
        jPanel1.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Square721 BT", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("ID");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(190, 220, 68, 30);

        refreshminum.setFont(new java.awt.Font("Square721 BT", 1, 24)); // NOI18N
        refreshminum.setText("Refresh");
        refreshminum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshminumActionPerformed(evt);
            }
        });
        jPanel1.add(refreshminum);
        refreshminum.setBounds(190, 910, 127, 39);

        txtid.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel1.add(txtid);
        txtid.setBounds(430, 220, 250, 40);

        tmbhminum.setFont(new java.awt.Font("Square721 BT", 1, 24)); // NOI18N
        tmbhminum.setText("Tambah");
        tmbhminum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tmbhminumActionPerformed(evt);
            }
        });
        jPanel1.add(tmbhminum);
        tmbhminum.setBounds(400, 910, 131, 39);

        txtnohp.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel1.add(txtnohp);
        txtnohp.setBounds(430, 480, 250, 40);

        tabelminum.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        tabelminum.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nama", "Alamat", "Email", "Password", "No. Handphone", "Tanggal"
            }
        ));
        tabelminum.setRowHeight(50);
        tabelminum.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tabelminumMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tabelminum);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(190, 570, 1310, 320);

        editminum.setFont(new java.awt.Font("Square721 BT", 1, 24)); // NOI18N
        editminum.setText("Edit");
        editminum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editminumActionPerformed(evt);
            }
        });
        jPanel1.add(editminum);
        editminum.setBounds(1190, 910, 101, 39);

        jLabel5.setFont(new java.awt.Font("Square721 BT", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Alamat");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(700, 280, 90, 30);

        jLabel4.setFont(new java.awt.Font("Square721 BT", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Email");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(190, 350, 64, 30);

        dataminuman.setFont(new java.awt.Font("Square721 BT", 1, 24)); // NOI18N
        dataminuman.setText("Tampilkan Data");
        dataminuman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataminumanActionPerformed(evt);
            }
        });
        jPanel1.add(dataminuman);
        dataminuman.setBounds(1530, 700, 219, 60);

        txtemail.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel1.add(txtemail);
        txtemail.setBounds(430, 350, 250, 40);

        hapusminum.setFont(new java.awt.Font("Square721 BT", 1, 24)); // NOI18N
        hapusminum.setText("Hapus");
        hapusminum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusminumActionPerformed(evt);
            }
        });
        jPanel1.add(hapusminum);
        hapusminum.setBounds(1380, 910, 114, 39);

        kembali.setFont(new java.awt.Font("Square721 BT", 1, 24)); // NOI18N
        kembali.setText("Kembali");
        kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembaliActionPerformed(evt);
            }
        });
        jPanel1.add(kembali);
        kembali.setBounds(30, 20, 130, 50);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 60)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("DATA PETUGAS");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(770, 30, 470, 73);

        txtfoto.setEditable(false);
        txtfoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfotoActionPerformed(evt);
            }
        });
        jPanel1.add(txtfoto);
        txtfoto.setBounds(1280, 480, 219, 40);

        btncari.setFont(new java.awt.Font("Square721 BT", 1, 24)); // NOI18N
        btncari.setText("CARI");
        btncari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncariActionPerformed(evt);
            }
        });
        jPanel1.add(btncari);
        btncari.setBounds(1530, 320, 185, 39);

        labelfoto.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 4, true));
        jPanel1.add(labelfoto);
        labelfoto.setBounds(1280, 200, 219, 250);

        jLabel6.setFont(new java.awt.Font("Square721 BT", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Password");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(190, 420, 118, 40);

        txtpass.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel1.add(txtpass);
        txtpass.setBounds(430, 420, 250, 40);

        jLabel7.setFont(new java.awt.Font("Square721 BT", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("No. Handphone");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(190, 480, 190, 40);

        txtalamat.setColumns(1);
        txtalamat.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        txtalamat.setRows(1);
        txtalamat.setTabSize(1);
        jScrollPane2.setViewportView(txtalamat);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(840, 270, 420, 250);

        jLabel8.setFont(new java.awt.Font("Square721 BT", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Nama");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(190, 280, 68, 30);

        txtnama.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel1.add(txtnama);
        txtnama.setBounds(430, 280, 250, 40);

        btnget.setFont(new java.awt.Font("Square721 BT", 1, 24)); // NOI18N
        btnget.setText("GET");
        btnget.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngetActionPerformed(evt);
            }
        });
        jPanel1.add(btnget);
        btnget.setBounds(700, 220, 90, 40);

        jLabel9.setFont(new java.awt.Font("Square721 BT", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText(":");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(810, 280, 20, 30);

        jLabel10.setFont(new java.awt.Font("Square721 BT", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText(":");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(390, 220, 20, 40);

        jLabel11.setFont(new java.awt.Font("Square721 BT", 0, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText(":");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(390, 280, 20, 40);

        jLabel12.setFont(new java.awt.Font("Square721 BT", 0, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText(":");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(390, 350, 20, 40);

        jLabel13.setFont(new java.awt.Font("Square721 BT", 0, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText(":");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(390, 420, 20, 40);

        jLabel14.setFont(new java.awt.Font("Square721 BT", 0, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText(":");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(390, 480, 20, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tabelminumMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelminumMousePressed
        int tabel = tabelminum.getSelectedRow();
  txtid.setText(tabelminum.getValueAt(tabel, 0).toString());
  txtnama.setText(tabelminum.getValueAt(tabel, 1).toString());
  txtalamat.setText(tabelminum.getValueAt(tabel, 2).toString());
  txtemail.setText(tabelminum.getValueAt(tabel, 3).toString());
  txtpass.setText(tabelminum.getValueAt(tabel, 4).toString());
  txtnohp.setText(tabelminum.getValueAt(tabel, 5).toString());
  
    }//GEN-LAST:event_tabelminumMousePressed

    private void tmbhminumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tmbhminumActionPerformed
        Buatlagi();
    }//GEN-LAST:event_tmbhminumActionPerformed

    private void editminumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editminumActionPerformed
        editdata();
    }//GEN-LAST:event_editminumActionPerformed

    private void hapusminumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusminumActionPerformed
        Tabelklik();
    }//GEN-LAST:event_hapusminumActionPerformed

    private void dataminumanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataminumanActionPerformed
        tampilkandata();
    }//GEN-LAST:event_dataminumanActionPerformed

    private void refreshminumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshminumActionPerformed
        txtid.setText("");
        txtnama.setText("");
        txtemail.setText("");
        txtnohp.setText("");
        txtfoto.setText("");
        txtpass.setText("");
        txtalamat.setText("");
    }//GEN-LAST:event_refreshminumActionPerformed

    private void kembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembaliActionPerformed
        new menuadmin().setVisible(true);
    }//GEN-LAST:event_kembaliActionPerformed

    private void txtfotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfotoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfotoActionPerformed

    private void btncariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncariActionPerformed
        jfc=new JFileChooser();
        if(jfc.showOpenDialog(labelfoto)==JFileChooser.APPROVE_OPTION){
            
            Toolkit toolkit=Toolkit.getDefaultToolkit();
            Image image=toolkit.getImage(jfc.getSelectedFile().getAbsolutePath());
            Image imagedResized=image.getScaledInstance(200, 250, Image.SCALE_DEFAULT);
            ImageIcon imageIcon=new ImageIcon(imagedResized);
            
            labelfoto.setIcon(imageIcon);
            txtfoto.setText(jfc.getSelectedFile().getName());
            
            file =new File(jfc.getSelectedFile().getPath());
        }
    }//GEN-LAST:event_btncariActionPerformed

    private void btngetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngetActionPerformed
        id();
    }//GEN-LAST:event_btngetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(datapetugas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(datapetugas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(datapetugas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(datapetugas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new datapetugas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncari;
    private javax.swing.JButton btnget;
    private javax.swing.JButton dataminuman;
    private javax.swing.JButton editminum;
    private javax.swing.JButton hapusminum;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton kembali;
    private javax.swing.JLabel labelfoto;
    private javax.swing.JButton refreshminum;
    private javax.swing.JTable tabelminum;
    private javax.swing.JButton tmbhminum;
    private javax.swing.JTextArea txtalamat;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtfoto;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtnama;
    private javax.swing.JTextField txtnohp;
    private javax.swing.JTextField txtpass;
    // End of variables declaration//GEN-END:variables
private void open_db(){
    try{
        Class.forName("com.mysql.jdbc.Driver");
        koneksi=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/proyek", "root", "");
        st=(Statement)koneksi.createStatement();
    }catch(Exception a){
        JOptionPane.showMessageDialog(null, "Koneksi Gagal");
        System.out.println(a.getMessage());
        
    }

}
private void tampilkandata() {
        
        DefaultTableModel tabelminuman = new DefaultTableModel();
        tabelminuman.addColumn("ID");
        tabelminuman.addColumn("Nama");
        tabelminuman.addColumn("Alamat");
        tabelminuman.addColumn("Username");
        tabelminuman.addColumn("Password");
        tabelminuman.addColumn("No. Handphone");
        tabelminuman.addColumn("Tanggal");
        
        try {
            open_db();
             String sql = "select * from data_petugas";
            st= (Statement) koneksi.createStatement();
            ResultSet rs=st.executeQuery(sql);
            while (rs.next()) {
                Object[] a =new Object[7];
                a[0] = rs.getString("id");
                a[1] = rs.getString("nama");
                a[2] = rs.getString("alamat");
                a[3] = rs.getString("username");
                a[4] = rs.getString("pass");
                a[5] = rs.getString("no_hp");
                a[6] = rs.getString("tanggal");
                
                tabelminuman.addRow(a);
                
            }
           tabelminum.setModel(tabelminuman);
        } catch (Exception e) {
        }
    }
private void id() {
        try {
            open_db();
            String sql = "SELECT * FROM data_petugas ORDER by id desc";
            st = (Statement) koneksi.createStatement();
            ResultSet r=st.executeQuery(sql);

            if (r.next()) {
                
                
                String nofak = r.getString("id").substring(1);
                String AN = "" + (Integer.parseInt(nofak) + 1);
                String Nol = "";

                if (AN.length() == 1) {
                    Nol = "00";
                } else if (AN.length() == 2) {
                    Nol = "0";
                } else if (AN.length() == 3) {
                    Nol = "";
                } 


                txtid.setText(Nol + AN);
            } else {
                txtid.setText("001");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
private void Tabelklik(){
        int pilih = tabelminum.getSelectedRow();
        String id = (String) tabelminum.getValueAt(pilih, 0);
         try {
            Statement state  = database.GetConnection().createStatement();
            state.executeUpdate("delete from data_petugas where id='"+id+"';");
            JOptionPane.showMessageDialog(this, "Data Berhasil Dihapus !");
            tampilkandata();
            
            state.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Data Gagal Dihapus !");
        }
    }
}
