/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyek;

import database.database;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.table.TableModel;
import javax.swing.JFileChooser;

/**
 *
 * @author dell
 */
public class inventori extends javax.swing.JFrame {
    private Connection koneksi;
    private Statement st;
    JFileChooser jfc;
    File file;
    /**
     * Creates new form produk
     */
    public inventori() {
        initComponents();
    }
    
    
    
    public void Buatlagi(){
       String id = txtid.getText();
       String nama = txtnama.getText();
       String jumlah = txtjumlah.getText();
        try{
        Statement state  = database.GetConnection().createStatement();
        state.executeUpdate("insert into inventori values ('"+id+"','"+nama+"','"+jumlah+"',NOW())");
        JOptionPane.showMessageDialog(this, "Data Berhasil Dibuat !");
        try { 
        }catch (Exception e) {
        }
        
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, "Silahkan Cek Ulang!");
        }
    }
    
    public void editdata(){
       String id = txtid.getText();
       String nama = txtnama.getText();
       String jumlah = txtjumlah.getText();
        try{
        Statement state  = database.GetConnection().createStatement();
        state.executeUpdate("update inventori set nama_barang='"+nama+"', jumlah_barang='"+jumlah+"'where id='"+id+"';");
        JOptionPane.showMessageDialog(this, "Data Berhasil DiUpdate !");
         
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, "Gak Bisa Bro!");
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        refreshminum = new javax.swing.JButton();
        txtid = new javax.swing.JTextField();
        tmbhminum = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelminum = new javax.swing.JTable();
        editminum = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        dataminuman = new javax.swing.JButton();
        txtjumlah = new javax.swing.JTextField();
        hapusminum = new javax.swing.JButton();
        kembali = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtnama = new javax.swing.JTextField();
        btnget = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 255));

        jPanel1.setBackground(new java.awt.Color(0, 0, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(1920, 1080));
        jPanel1.setMinimumSize(new java.awt.Dimension(1920, 1080));
        jPanel1.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Square721 BT", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("ID");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(300, 220, 68, 30);

        refreshminum.setFont(new java.awt.Font("Square721 BT", 1, 24)); // NOI18N
        refreshminum.setText("Refresh");
        refreshminum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshminumActionPerformed(evt);
            }
        });
        jPanel1.add(refreshminum);
        refreshminum.setBounds(300, 770, 127, 39);

        txtid.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel1.add(txtid);
        txtid.setBounds(560, 220, 250, 40);

        tmbhminum.setFont(new java.awt.Font("Square721 BT", 1, 24)); // NOI18N
        tmbhminum.setText("Tambah");
        tmbhminum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tmbhminumActionPerformed(evt);
            }
        });
        jPanel1.add(tmbhminum);
        tmbhminum.setBounds(510, 770, 131, 39);

        tabelminum.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        tabelminum.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Nama Barang", "Jumlah Barang", "Tanggal"
            }
        ));
        tabelminum.setRowHeight(50);
        tabelminum.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tabelminumMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tabelminum);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(300, 430, 1310, 320);

        editminum.setFont(new java.awt.Font("Square721 BT", 1, 24)); // NOI18N
        editminum.setText("Edit");
        editminum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editminumActionPerformed(evt);
            }
        });
        jPanel1.add(editminum);
        editminum.setBounds(1300, 770, 101, 39);

        jLabel4.setFont(new java.awt.Font("Square721 BT", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Jumlah Barang");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(300, 360, 190, 30);

        dataminuman.setFont(new java.awt.Font("Square721 BT", 1, 24)); // NOI18N
        dataminuman.setText("Tampilkan Data");
        dataminuman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataminumanActionPerformed(evt);
            }
        });
        jPanel1.add(dataminuman);
        dataminuman.setBounds(840, 340, 219, 60);

        txtjumlah.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel1.add(txtjumlah);
        txtjumlah.setBounds(560, 360, 250, 40);

        hapusminum.setFont(new java.awt.Font("Square721 BT", 1, 24)); // NOI18N
        hapusminum.setText("Hapus");
        hapusminum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusminumActionPerformed(evt);
            }
        });
        jPanel1.add(hapusminum);
        hapusminum.setBounds(1490, 770, 114, 39);

        kembali.setFont(new java.awt.Font("Square721 BT", 1, 24)); // NOI18N
        kembali.setText("Kembali");
        kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembaliActionPerformed(evt);
            }
        });
        jPanel1.add(kembali);
        kembali.setBounds(30, 20, 130, 50);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 60)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("INVENTORI");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(770, 30, 360, 73);

        jLabel8.setFont(new java.awt.Font("Square721 BT", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Nama Barang");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(300, 290, 170, 30);

        txtnama.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel1.add(txtnama);
        txtnama.setBounds(560, 290, 250, 40);

        btnget.setFont(new java.awt.Font("Square721 BT", 1, 24)); // NOI18N
        btnget.setText("GET");
        btnget.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngetActionPerformed(evt);
            }
        });
        jPanel1.add(btnget);
        btnget.setBounds(840, 219, 93, 40);

        jLabel9.setFont(new java.awt.Font("Square721 BT", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText(":");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(520, 360, 20, 40);

        jLabel10.setFont(new java.awt.Font("Square721 BT", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText(":");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(520, 220, 20, 30);

        jLabel11.setFont(new java.awt.Font("Square721 BT", 0, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText(":");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(520, 290, 20, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tabelminumMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelminumMousePressed
        int tabel = tabelminum.getSelectedRow();
  txtid.setText(tabelminum.getValueAt(tabel, 0).toString());
  txtnama.setText(tabelminum.getValueAt(tabel, 1).toString());
  txtjumlah.setText(tabelminum.getValueAt(tabel, 2).toString());
  
    }//GEN-LAST:event_tabelminumMousePressed

    private void tmbhminumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tmbhminumActionPerformed
        Buatlagi();
    }//GEN-LAST:event_tmbhminumActionPerformed

    private void editminumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editminumActionPerformed
        editdata();
    }//GEN-LAST:event_editminumActionPerformed

    private void hapusminumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusminumActionPerformed
        Tabelklik();
    }//GEN-LAST:event_hapusminumActionPerformed

    private void dataminumanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataminumanActionPerformed
        tampilkandata();
    }//GEN-LAST:event_dataminumanActionPerformed

    private void refreshminumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshminumActionPerformed
        txtid.setText("");
        txtnama.setText("");
        txtjumlah.setText("");
    }//GEN-LAST:event_refreshminumActionPerformed

    private void kembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembaliActionPerformed
        new menuadmin().setVisible(true);
    }//GEN-LAST:event_kembaliActionPerformed

    private void btngetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngetActionPerformed
        id();
    }//GEN-LAST:event_btngetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(inventori.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(inventori.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(inventori.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(inventori.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new inventori().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnget;
    private javax.swing.JButton dataminuman;
    private javax.swing.JButton editminum;
    private javax.swing.JButton hapusminum;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton kembali;
    private javax.swing.JButton refreshminum;
    private javax.swing.JTable tabelminum;
    private javax.swing.JButton tmbhminum;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtjumlah;
    private javax.swing.JTextField txtnama;
    // End of variables declaration//GEN-END:variables
private void open_db(){
    try{
        Class.forName("com.mysql.jdbc.Driver");
        koneksi=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/proyek", "root", "");
        st=(Statement)koneksi.createStatement();
    }catch(Exception a){
        JOptionPane.showMessageDialog(null, "Koneksi Gagal");
        System.out.println(a.getMessage());
        
    }

}
private void tampilkandata() {
        
        DefaultTableModel tabelminuman = new DefaultTableModel();
        tabelminuman.addColumn("ID");
        tabelminuman.addColumn("Nama Barang");
        tabelminuman.addColumn("Jumlah Barang");
        tabelminuman.addColumn("Tanggal");
        
        try {
            open_db();
             String sql = "select * from inventori";
            st= (Statement) koneksi.createStatement();
            ResultSet rs=st.executeQuery(sql);
            while (rs.next()) {
                Object[] a =new Object[4];
                a[0] = rs.getString("id");
                a[1] = rs.getString("nama_barang");
                a[2] = rs.getString("jumlah_barang");
                a[3] = rs.getString("tanggal");
                
                tabelminuman.addRow(a);
                
            }
           tabelminum.setModel(tabelminuman);
        } catch (Exception e) {
        }
    }
private void id() {
        try {
            open_db();
            String sql = "SELECT * FROM inventori ORDER by id desc";
            st = (Statement) koneksi.createStatement();
            ResultSet r=st.executeQuery(sql);

            if (r.next()) {
                
                
                String nofak = r.getString("id").substring(1);
                String AN = "" + (Integer.parseInt(nofak) + 1);
                String Nol = "";

                if (AN.length() == 1) {
                    Nol = "00";
                } else if (AN.length() == 2) {
                    Nol = "0";
                } else if (AN.length() == 3) {
                    Nol = "";
                } 


                txtid.setText(Nol + AN);
            } else {
                txtid.setText("001");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
private void Tabelklik(){
        int pilih = tabelminum.getSelectedRow();
        String id = (String) tabelminum.getValueAt(pilih, 0);
         try {
            Statement state  = database.GetConnection().createStatement();
            state.executeUpdate("delete from inventori where id='"+id+"';");
            JOptionPane.showMessageDialog(this, "Data Berhasil Dihapus !");
            tampilkandata();
            
            state.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Data Gagal Dihapus !");
        }
    }
}
