/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyek;

/**
 *
 * @author dell
 */
public class menuadmin extends javax.swing.JFrame {

    /**
     * Creates new form menuadmin
     */
    public menuadmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        btninventori = new javax.swing.JButton();
        btnriwayattrans = new javax.swing.JButton();
        btnmenuproduk = new javax.swing.JButton();
        btnlaporan = new javax.swing.JButton();
        btndatapetugas = new javax.swing.JButton();
        btnprofilusaha = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setSize(new java.awt.Dimension(0, 0));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Square721 BT", 1, 100)); // NOI18N
        jLabel1.setText("MENU");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(800, 50, 340, 100);

        jButton7.setBackground(new java.awt.Color(255, 0, 0));
        jButton7.setFont(new java.awt.Font("Square721 BT", 1, 24)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("LOGOUT");
        jButton7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 4, true));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7);
        jButton7.setBounds(1720, 960, 150, 60);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/menuuuu.png"))); // NOI18N
        jPanel1.add(jLabel8);
        jLabel8.setBounds(0, 0, 1920, 201);

        btninventori.setFont(new java.awt.Font("Square721 BT", 1, 36)); // NOI18N
        btninventori.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pesanan.png"))); // NOI18N
        btninventori.setText("INVENTORI");
        btninventori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btninventoriActionPerformed(evt);
            }
        });
        jPanel1.add(btninventori);
        btninventori.setBounds(310, 470, 551, 109);

        btnriwayattrans.setFont(new java.awt.Font("Square721 BT", 1, 36)); // NOI18N
        btnriwayattrans.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/riwayat transaksi.png"))); // NOI18N
        btnriwayattrans.setText("RIWAYAT TRANSAKSI");
        btnriwayattrans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnriwayattransActionPerformed(evt);
            }
        });
        jPanel1.add(btnriwayattrans);
        btnriwayattrans.setBounds(310, 280, 551, 109);

        btnmenuproduk.setFont(new java.awt.Font("Square721 BT", 1, 36)); // NOI18N
        btnmenuproduk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/menuproduk.png"))); // NOI18N
        btnmenuproduk.setText("MENU PRODUK");
        btnmenuproduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmenuprodukActionPerformed(evt);
            }
        });
        jPanel1.add(btnmenuproduk);
        btnmenuproduk.setBounds(1080, 280, 551, 109);

        btnlaporan.setFont(new java.awt.Font("Square721 BT", 1, 36)); // NOI18N
        btnlaporan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pencatatan.png"))); // NOI18N
        btnlaporan.setText("LAPORAN");
        btnlaporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlaporanActionPerformed(evt);
            }
        });
        jPanel1.add(btnlaporan);
        btnlaporan.setBounds(310, 670, 551, 109);

        btndatapetugas.setFont(new java.awt.Font("Square721 BT", 1, 36)); // NOI18N
        btndatapetugas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/anggota.png"))); // NOI18N
        btndatapetugas.setText("DATA PETUGAS");
        btndatapetugas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndatapetugasActionPerformed(evt);
            }
        });
        jPanel1.add(btndatapetugas);
        btndatapetugas.setBounds(1080, 670, 551, 109);

        btnprofilusaha.setFont(new java.awt.Font("Square721 BT", 1, 36)); // NOI18N
        btnprofilusaha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/profil usaha.png"))); // NOI18N
        btnprofilusaha.setText("PROFIL USAHA");
        btnprofilusaha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprofilusahaActionPerformed(evt);
            }
        });
        jPanel1.add(btnprofilusaha);
        btnprofilusaha.setBounds(1080, 470, 551, 109);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/menu2.png"))); // NOI18N
        jPanel1.add(jLabel7);
        jLabel7.setBounds(0, 880, 1920, 200);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1920, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1080, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        new loginadmin().setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void btnriwayattransActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnriwayattransActionPerformed
        new riwayattransaksi().setVisible(true);
    }//GEN-LAST:event_btnriwayattransActionPerformed

    private void btndatapetugasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndatapetugasActionPerformed
        new datapetugas().setVisible(true);
    }//GEN-LAST:event_btndatapetugasActionPerformed

    private void btnmenuprodukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmenuprodukActionPerformed
        new produk().setVisible(true);
    }//GEN-LAST:event_btnmenuprodukActionPerformed

    private void btninventoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btninventoriActionPerformed
        new inventori().setVisible(true);
    }//GEN-LAST:event_btninventoriActionPerformed

    private void btnlaporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlaporanActionPerformed
        new laporan().setVisible(true);
    }//GEN-LAST:event_btnlaporanActionPerformed

    private void btnprofilusahaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprofilusahaActionPerformed
        new profilusaha().setVisible(true);
    }//GEN-LAST:event_btnprofilusahaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuadmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuadmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuadmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuadmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menuadmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btndatapetugas;
    private javax.swing.JButton btninventori;
    private javax.swing.JButton btnlaporan;
    private javax.swing.JButton btnmenuproduk;
    private javax.swing.JButton btnprofilusaha;
    private javax.swing.JButton btnriwayattrans;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
