/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyek;

import database.database;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.table.TableModel;
import javax.swing.JFileChooser;

/**
 *
 * @author dell
 */
public class produk extends javax.swing.JFrame {
    private Connection koneksi;
    private Statement st;
    JFileChooser jfc;
    File file;
    /**
     * Creates new form produk
     */
    public produk() {
        initComponents();
    }
    
    
    
    public void BuatMinuman(){
       String id_minum = idminum.getText();
       String id_prod = idprodmnm.getText();
       String namaminum = namamnm.getText();
       String image = txtimage.getText();
       String status = (String) txtstatusmakan.getSelectedItem();
       image = image.replace("\\","\\\\");
        try{
        Statement state  = database.GetConnection().createStatement();
        state.executeUpdate("insert into minuman values ('"+id_minum+"','"+id_prod+"','"+namaminum+"','"+image+"','"+status+"')");
        JOptionPane.showMessageDialog(this, "Data Berhasil Dibuat !");
        
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Silahkan klik Update NEW !");
        }
    }
    public void BuatMakanan(){
       String id_makan = idmakan.getText();
       String id_prodmkn = idprodmkn.getText();
       String namamakan = namamkn.getText();
       String image = txtimagemakan.getText();
       String status = (String) txtstatusmakan.getSelectedItem();
       image = image.replace("\\","\\\\");
        try{
        Statement state  = database.GetConnection().createStatement();
        state.executeUpdate("insert into makanan values ('"+id_makan+"','"+id_prodmkn+"','"+namamakan+"','"+image+"','"+status+"')");
        JOptionPane.showMessageDialog(this, "Data Berhasil Dibuat !");
        
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Silahkan klik Update NEW !");
        }
    }
    public void editminuman(){
       String id_minum = idminum.getText();
       String id_prod = idprodmnm.getText();
       String namaminum = namamnm.getText();
       String image = txtimage.getText();
       String status = (String) txtstatusmakan.getSelectedItem();
       image = image.replace("\\","\\\\");
        try{
        Statement state  = database.GetConnection().createStatement();
        state.executeUpdate("update minuman set image='"+image+"', nama_minuman='"+namaminum+"', statuss='"+status+"' where id_minuman='"+id_minum+"';");
        JOptionPane.showMessageDialog(this, "Data Berhasil DiUpdate !");
         
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, "Gak Bisa Bro!");
        }
    }
    public void editmakanan(){
       String id_makan = idmakan.getText();
       String id_prodmkn = idprodmkn.getText();
       String namamakan = namamkn.getText();
       String image = txtimagemakan.getText();
       String status = (String) txtstatusmakan.getSelectedItem();
       image = image.replace("\\","\\\\");
        try{
        Statement state  = database.GetConnection().createStatement();
        state.executeUpdate("update makanan set image='"+image+"', nama_makanan='"+namamakan+"', statuss='"+status+"' where id_makanan='"+id_makan+"';");
        JOptionPane.showMessageDialog(this, "Data Berhasil DiUpdate !");
         
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, "Silahkan klik Update NEW !");
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        refreshminum = new javax.swing.JButton();
        idminum = new javax.swing.JTextField();
        tmbhminum = new javax.swing.JButton();
        namamnm = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelminum = new javax.swing.JTable();
        editminum = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        dataminuman = new javax.swing.JButton();
        idprodmnm = new javax.swing.JTextField();
        hapusminum = new javax.swing.JButton();
        kembali = new javax.swing.JButton();
        refreshmakan = new javax.swing.JButton();
        datamakanan = new javax.swing.JButton();
        hapusmkn = new javax.swing.JButton();
        editmkn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelmakan = new javax.swing.JTable();
        tambahmkn = new javax.swing.JButton();
        namamkn = new javax.swing.JTextField();
        idprodmkn = new javax.swing.JTextField();
        idmakan = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtimage = new javax.swing.JTextField();
        btncari = new javax.swing.JButton();
        labelimage = new javax.swing.JLabel();
        labelimagemakan = new javax.swing.JLabel();
        txtimagemakan = new javax.swing.JTextField();
        btncarimakan = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtstatusmakan = new javax.swing.JComboBox<>();
        txtstatus1 = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 255));

        jPanel1.setBackground(new java.awt.Color(0, 0, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(1920, 1080));
        jPanel1.setMinimumSize(new java.awt.Dimension(1920, 1080));
        jPanel1.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Square721 BT", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("ID Minuman");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(230, 210, 144, 30);

        refreshminum.setFont(new java.awt.Font("Square721 BT", 1, 24)); // NOI18N
        refreshminum.setText("Refresh");
        refreshminum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshminumActionPerformed(evt);
            }
        });
        jPanel1.add(refreshminum);
        refreshminum.setBounds(230, 490, 127, 39);

        idminum.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel1.add(idminum);
        idminum.setBounds(470, 210, 250, 35);

        tmbhminum.setFont(new java.awt.Font("Square721 BT", 1, 24)); // NOI18N
        tmbhminum.setText("Tambah");
        tmbhminum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tmbhminumActionPerformed(evt);
            }
        });
        jPanel1.add(tmbhminum);
        tmbhminum.setBounds(440, 490, 131, 39);

        namamnm.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel1.add(namamnm);
        namamnm.setBounds(470, 340, 250, 40);

        tabelminum.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        tabelminum.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID Minuman", "ID Produk", "Nama Minuman", "Status"
            }
        ));
        tabelminum.setRowHeight(50);
        tabelminum.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tabelminumMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tabelminum);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(740, 210, 532, 230);

        editminum.setFont(new java.awt.Font("Square721 BT", 1, 24)); // NOI18N
        editminum.setText("Edit");
        editminum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editminumActionPerformed(evt);
            }
        });
        jPanel1.add(editminum);
        editminum.setBounds(650, 490, 101, 39);

        jLabel5.setFont(new java.awt.Font("Square721 BT", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Nama Minuman");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(230, 340, 184, 40);

        jLabel2.setFont(new java.awt.Font("Square721 BT", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("MINUMAN");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(890, 140, 204, 44);

        jLabel4.setFont(new java.awt.Font("Square721 BT", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("ID Produk");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(230, 280, 122, 30);

        dataminuman.setFont(new java.awt.Font("Square721 BT", 1, 24)); // NOI18N
        dataminuman.setText("Tampilkan Data");
        dataminuman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataminumanActionPerformed(evt);
            }
        });
        jPanel1.add(dataminuman);
        dataminuman.setBounds(1050, 490, 219, 39);

        idprodmnm.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel1.add(idprodmnm);
        idprodmnm.setBounds(470, 270, 250, 40);

        hapusminum.setFont(new java.awt.Font("Square721 BT", 1, 24)); // NOI18N
        hapusminum.setText("Hapus");
        hapusminum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusminumActionPerformed(evt);
            }
        });
        jPanel1.add(hapusminum);
        hapusminum.setBounds(850, 490, 114, 39);

        kembali.setFont(new java.awt.Font("Square721 BT", 1, 24)); // NOI18N
        kembali.setText("Kembali");
        kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembaliActionPerformed(evt);
            }
        });
        jPanel1.add(kembali);
        kembali.setBounds(30, 20, 130, 50);

        refreshmakan.setFont(new java.awt.Font("Square721 BT", 1, 24)); // NOI18N
        refreshmakan.setText("Refresh");
        refreshmakan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshmakanActionPerformed(evt);
            }
        });
        jPanel1.add(refreshmakan);
        refreshmakan.setBounds(230, 920, 135, 39);

        datamakanan.setFont(new java.awt.Font("Square721 BT", 1, 24)); // NOI18N
        datamakanan.setText("Tampilkan Data");
        datamakanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datamakananActionPerformed(evt);
            }
        });
        jPanel1.add(datamakanan);
        datamakanan.setBounds(1050, 920, 219, 39);

        hapusmkn.setFont(new java.awt.Font("Square721 BT", 1, 24)); // NOI18N
        hapusmkn.setText("Hapus");
        hapusmkn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusmknActionPerformed(evt);
            }
        });
        jPanel1.add(hapusmkn);
        hapusmkn.setBounds(850, 920, 123, 39);

        editmkn.setFont(new java.awt.Font("Square721 BT", 1, 24)); // NOI18N
        editmkn.setText("Edit");
        editmkn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editmknActionPerformed(evt);
            }
        });
        jPanel1.add(editmkn);
        editmkn.setBounds(660, 920, 100, 39);

        tabelmakan.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        tabelmakan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID Makanan", "ID Produk", "Nama Makanan", "Status"
            }
        ));
        tabelmakan.setRowHeight(50);
        tabelmakan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tabelmakanMousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(tabelmakan);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(740, 640, 529, 240);

        tambahmkn.setFont(new java.awt.Font("Square721 BT", 1, 24)); // NOI18N
        tambahmkn.setText("Tambah");
        tambahmkn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahmknActionPerformed(evt);
            }
        });
        jPanel1.add(tambahmkn);
        tambahmkn.setBounds(440, 920, 140, 39);

        namamkn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel1.add(namamkn);
        namamkn.setBounds(470, 780, 250, 40);

        idprodmkn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel1.add(idprodmkn);
        idprodmkn.setBounds(470, 710, 250, 40);

        idmakan.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel1.add(idmakan);
        idmakan.setBounds(470, 640, 250, 40);

        jLabel9.setFont(new java.awt.Font("Square721 BT", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Nama Makanan");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(230, 780, 184, 30);

        jLabel8.setFont(new java.awt.Font("Square721 BT", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("ID Produk");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(230, 710, 122, 30);

        jLabel7.setFont(new java.awt.Font("Square721 BT", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("ID Makanan");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(230, 650, 144, 30);

        jLabel6.setFont(new java.awt.Font("Square721 BT", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("MAKANAN");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(890, 570, 206, 44);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 60)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("PRODUK");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(860, 30, 260, 73);

        txtimage.setEditable(false);
        txtimage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtimageActionPerformed(evt);
            }
        });
        jPanel1.add(txtimage);
        txtimage.setBounds(1320, 490, 219, 40);

        btncari.setFont(new java.awt.Font("Square721 BT", 1, 24)); // NOI18N
        btncari.setText("CARI");
        btncari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncariActionPerformed(evt);
            }
        });
        jPanel1.add(btncari);
        btncari.setBounds(1560, 300, 185, 39);

        labelimage.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 4, true));
        jPanel1.add(labelimage);
        labelimage.setBounds(1320, 180, 219, 260);

        labelimagemakan.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 4, true));
        jPanel1.add(labelimagemakan);
        labelimagemakan.setBounds(1320, 630, 220, 250);

        txtimagemakan.setEditable(false);
        jPanel1.add(txtimagemakan);
        txtimagemakan.setBounds(1320, 920, 220, 40);

        btncarimakan.setFont(new java.awt.Font("Square721 BT", 1, 24)); // NOI18N
        btncarimakan.setText("CARI");
        btncarimakan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncarimakanActionPerformed(evt);
            }
        });
        jPanel1.add(btncarimakan);
        btncarimakan.setBounds(1560, 750, 190, 39);

        jLabel10.setFont(new java.awt.Font("Square721 BT", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Status");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(230, 840, 180, 40);

        jLabel11.setFont(new java.awt.Font("Square721 BT", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Status");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(230, 400, 180, 40);

        txtstatusmakan.setFont(new java.awt.Font("Square721 BT", 1, 24)); // NOI18N
        txtstatusmakan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ada", "Habis" }));
        jPanel1.add(txtstatusmakan);
        txtstatusmakan.setBounds(470, 840, 250, 40);

        txtstatus1.setFont(new java.awt.Font("Square721 BT", 1, 24)); // NOI18N
        txtstatus1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ada", "Habis" }));
        jPanel1.add(txtstatus1);
        txtstatus1.setBounds(470, 400, 250, 40);

        jLabel12.setFont(new java.awt.Font("Square721 BT", 0, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText(":");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(440, 840, 20, 30);

        jLabel13.setFont(new java.awt.Font("Square721 BT", 0, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText(":");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(440, 210, 20, 30);

        jLabel14.setFont(new java.awt.Font("Square721 BT", 0, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText(":");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(440, 270, 20, 30);

        jLabel15.setFont(new java.awt.Font("Square721 BT", 0, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText(":");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(440, 340, 20, 30);

        jLabel16.setFont(new java.awt.Font("Square721 BT", 0, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText(":");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(440, 400, 20, 30);

        jLabel17.setFont(new java.awt.Font("Square721 BT", 0, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText(":");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(440, 640, 20, 30);

        jLabel18.setFont(new java.awt.Font("Square721 BT", 0, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText(":");
        jPanel1.add(jLabel18);
        jLabel18.setBounds(440, 710, 20, 30);

        jLabel19.setFont(new java.awt.Font("Square721 BT", 0, 24)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText(":");
        jPanel1.add(jLabel19);
        jLabel19.setBounds(440, 780, 20, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tabelminumMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelminumMousePressed
        int tabel = tabelminum.getSelectedRow();
  idminum.setText(tabelminum.getValueAt(tabel, 0).toString());
  idprodmnm.setText(tabelminum.getValueAt(tabel, 1).toString());
  namamnm.setText(tabelminum.getValueAt(tabel, 2).toString());
    }//GEN-LAST:event_tabelminumMousePressed

    private void tabelmakanMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelmakanMousePressed
            int tabel = tabelmakan.getSelectedRow();
  idmakan.setText(tabelmakan.getValueAt(tabel, 0).toString());
  idprodmkn.setText(tabelmakan.getValueAt(tabel, 1).toString());
  namamkn.setText(tabelmakan.getValueAt(tabel, 2).toString());
    }//GEN-LAST:event_tabelmakanMousePressed

    private void tmbhminumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tmbhminumActionPerformed
        BuatMinuman();
    }//GEN-LAST:event_tmbhminumActionPerformed

    private void tambahmknActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahmknActionPerformed
        BuatMakanan();
    }//GEN-LAST:event_tambahmknActionPerformed

    private void editminumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editminumActionPerformed
        editminuman();
    }//GEN-LAST:event_editminumActionPerformed

    private void editmknActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editmknActionPerformed
        editmakanan();
    }//GEN-LAST:event_editmknActionPerformed

    private void hapusminumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusminumActionPerformed
        String id_minum = idminum.getText();
        try {
            com.mysql.jdbc.Statement statement = (com.mysql.jdbc.Statement) database.GetConnection().createStatement();
            int pesan=JOptionPane.showConfirmDialog(null, "Yakin Data Akan Dihapus ?","Konfirmasi",JOptionPane.YES_NO_OPTION
            ,JOptionPane.QUESTION_MESSAGE);
             if(pesan==JOptionPane.YES_OPTION){
            if(statement.executeUpdate("DELETE from minuman where id_minuman= ('"+id_minum+"');")==1){
             }else{
                  JOptionPane.showMessageDialog(null, "Hapus Data Berhasil");
             }}
            idminum.setText("");
            idprodmnm.setText("");
            namamnm.setText("");
            txtstatusmakan.setSelectedItem("");
            
        }
        catch (Exception t){
            JOptionPane.showMessageDialog(null, "Data Gagal DiHapus");
        }
        
    }//GEN-LAST:event_hapusminumActionPerformed

    private void hapusmknActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusmknActionPerformed
        String id_makan = idmakan.getText();
        try {
            com.mysql.jdbc.Statement statement = (com.mysql.jdbc.Statement) database.GetConnection().createStatement();
            int pesan=JOptionPane.showConfirmDialog(null, "Yakin Data Akan Dihapus ?","Konfirmasi",JOptionPane.YES_NO_OPTION
            ,JOptionPane.QUESTION_MESSAGE);
             if(pesan==JOptionPane.YES_OPTION){
            if(statement.executeUpdate("DELETE from makanan where id_makanan= ('"+id_makan+"');")==1){
             }else{
                  JOptionPane.showMessageDialog(null, "Hapus Data Berhasil");
             }}
            idminum.setText("");
            idprodmnm.setText("");
            namamnm.setText("");
            txtstatusmakan.setSelectedItem("");
            
        }
        catch (Exception t){
            JOptionPane.showMessageDialog(null, "Data Gagal DiHapus");
        }
    }//GEN-LAST:event_hapusmknActionPerformed

    private void dataminumanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataminumanActionPerformed
        tampilkandata_minuman();
    }//GEN-LAST:event_dataminumanActionPerformed

    private void refreshminumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshminumActionPerformed
        idminum.setText("");
        idprodmnm.setText("");
        namamnm.setText("");
        txtimage.setText("");
    }//GEN-LAST:event_refreshminumActionPerformed

    private void datamakananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datamakananActionPerformed
        tampilkandata_makanan();
    }//GEN-LAST:event_datamakananActionPerformed

    private void refreshmakanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshmakanActionPerformed
        idmakan.setText("");
        idprodmkn.setText("");
        namamkn.setText("");
        txtimage.setText("");
    }//GEN-LAST:event_refreshmakanActionPerformed

    private void kembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembaliActionPerformed
        new menuadmin().setVisible(true);
    }//GEN-LAST:event_kembaliActionPerformed

    private void txtimageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtimageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtimageActionPerformed

    private void btncariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncariActionPerformed
        jfc=new JFileChooser();
        if(jfc.showOpenDialog(labelimage)==JFileChooser.APPROVE_OPTION){
            
            Toolkit toolkit=Toolkit.getDefaultToolkit();
            Image image=toolkit.getImage(jfc.getSelectedFile().getAbsolutePath());
            Image imagedResized=image.getScaledInstance(200, 250, Image.SCALE_DEFAULT);
            ImageIcon imageIcon=new ImageIcon(imagedResized);
            
            labelimage.setIcon(imageIcon);
            txtimage.setText(jfc.getSelectedFile().getName());
            
            file =new File(jfc.getSelectedFile().getPath());
        }
    }//GEN-LAST:event_btncariActionPerformed

    private void btncarimakanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncarimakanActionPerformed
        jfc=new JFileChooser();
        if(jfc.showOpenDialog(labelimagemakan)==JFileChooser.APPROVE_OPTION){
            
            Toolkit toolkit=Toolkit.getDefaultToolkit();
            Image image=toolkit.getImage(jfc.getSelectedFile().getAbsolutePath());
            Image imagedResized=image.getScaledInstance(200, 250, Image.SCALE_DEFAULT);
            ImageIcon imageIcon=new ImageIcon(imagedResized);
            
            labelimagemakan.setIcon(imageIcon);
            txtimagemakan.setText(jfc.getSelectedFile().getName());
            
            file =new File(jfc.getSelectedFile().getPath());
        }
    }//GEN-LAST:event_btncarimakanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(produk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(produk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(produk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(produk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new produk().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncari;
    private javax.swing.JButton btncarimakan;
    private javax.swing.JButton datamakanan;
    private javax.swing.JButton dataminuman;
    private javax.swing.JButton editminum;
    private javax.swing.JButton editmkn;
    private javax.swing.JButton hapusminum;
    private javax.swing.JButton hapusmkn;
    private javax.swing.JTextField idmakan;
    private javax.swing.JTextField idminum;
    private javax.swing.JTextField idprodmkn;
    private javax.swing.JTextField idprodmnm;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton kembali;
    private javax.swing.JLabel labelimage;
    private javax.swing.JLabel labelimagemakan;
    private javax.swing.JTextField namamkn;
    private javax.swing.JTextField namamnm;
    private javax.swing.JButton refreshmakan;
    private javax.swing.JButton refreshminum;
    private javax.swing.JTable tabelmakan;
    private javax.swing.JTable tabelminum;
    private javax.swing.JButton tambahmkn;
    private javax.swing.JButton tmbhminum;
    private javax.swing.JTextField txtimage;
    private javax.swing.JTextField txtimagemakan;
    private javax.swing.JComboBox<String> txtstatus1;
    private javax.swing.JComboBox<String> txtstatusmakan;
    // End of variables declaration//GEN-END:variables
private void open_db(){
    try{
        Class.forName("com.mysql.jdbc.Driver");
        koneksi=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/proyek", "root", "");
        st=(Statement)koneksi.createStatement();
    }catch(Exception a){
        JOptionPane.showMessageDialog(null, "Koneksi Gagal");
        System.out.println(a.getMessage());
        
    }

}
private void tampilkandata_minuman() {
        
        DefaultTableModel tabelminuman = new DefaultTableModel();
        tabelminuman.addColumn("ID Minuman");
        tabelminuman.addColumn("ID Produk");
        tabelminuman.addColumn("Nama Minuman");
        tabelminuman.addColumn("Status");
        
        try {
            open_db();
             String sql = "select * from minuman";
            st= (Statement) koneksi.createStatement();
            ResultSet rs=st.executeQuery(sql);
            while (rs.next()) {
                Object[] a =new Object[4];
                a[0] = rs.getString("id_minuman");
                a[1] = rs.getString("id_prod");
                a[2] = rs.getString("nama_minuman");
                a[3] = rs.getString("statuss");
                
                tabelminuman.addRow(a);
                
            }
           tabelminum.setModel(tabelminuman);
        } catch (Exception e) {
        }
    }
private void tampilkandata_makanan() {
        
        DefaultTableModel tabelmakanan = new DefaultTableModel();
        tabelmakanan.addColumn("ID Makanan");
        tabelmakanan.addColumn("ID Produk");
        tabelmakanan.addColumn("Nama Makanan");
        tabelmakanan.addColumn("Status");
        
        try {
            open_db();
             String sql = "select * from makanan";
            st= (Statement) koneksi.createStatement();
            ResultSet rs=st.executeQuery(sql);
            while (rs.next()) {
                Object[] a =new Object[4];
                a[0] = rs.getString("id_makanan");
                a[1] = rs.getString("id_prod");
                a[2] = rs.getString("nama_makanan");
                a[3] = rs.getString("statuss");
                
                tabelmakanan.addRow(a);
                
            }
           tabelmakan.setModel(tabelmakanan);
        } catch (Exception e) {
        }
    }
}
