/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyek;

import java.io.File;
import java.io.FileWriter;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author dell
 */
public class riwayattransaksi extends javax.swing.JFrame {
    private Connection koneksi;
    private Statement st;
    /**
     * Creates new form riwayattransaksi
     */
    public riwayattransaksi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        export = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl = new javax.swing.JTable();
        tampilkandata = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(0, 0));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(1920, 1080));
        jPanel1.setMinimumSize(new java.awt.Dimension(1920, 1080));
        jPanel1.setPreferredSize(new java.awt.Dimension(1920, 1080));
        jPanel1.setLayout(null);

        jButton2.setFont(new java.awt.Font("Square721 BT", 1, 24)); // NOI18N
        jButton2.setText("Kembali");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(1700, 939, 160, 50);

        export.setFont(new java.awt.Font("Square721 BT", 1, 24)); // NOI18N
        export.setText("Export Excel");
        export.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportActionPerformed(evt);
            }
        });
        jPanel1.add(export);
        export.setBounds(240, 269, 200, 60);

        tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        tbl.setRowHeight(50);
        jScrollPane1.setViewportView(tbl);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(240, 360, 1350, 430);

        tampilkandata.setFont(new java.awt.Font("Square721 BT", 1, 24)); // NOI18N
        tampilkandata.setText("Tampilkan data");
        tampilkandata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tampilkandataActionPerformed(evt);
            }
        });
        jPanel1.add(tampilkandata);
        tampilkandata.setBounds(810, 269, 240, 60);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/menuuuu.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1920, 201);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/menu2.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 880, 1920, 200);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tampilkandataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tampilkandataActionPerformed
        tampilkan_data();
    }//GEN-LAST:event_tampilkandataActionPerformed

    private void exportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportActionPerformed
        export();
    }//GEN-LAST:event_exportActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        menuadmin ma = new menuadmin();
        this.setVisible(false);
        ma.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed
private void export(){

        FileWriter fileWriter;

        JFileChooser chooser = new JFileChooser();

        chooser.setCurrentDirectory(new File("export_output/excel"));

        int retrival = chooser.showSaveDialog(null);

        if (retrival == JFileChooser.APPROVE_OPTION) {

            try{

                TableModel tModel = tbl.getModel();

                fileWriter = new FileWriter(new File(chooser.getSelectedFile() + ".csv"));           

            // write header

                for(int i = 0; i < tModel.getColumnCount(); i++){

                fileWriter.write(tModel.getColumnName(i).toUpperCase() + "\t");

            }

                fileWriter.write("\n");

            // write record

                for(int i=0; i < tModel.getRowCount(); i++) {

                for(int j=0; j < tModel.getColumnCount(); j++) {

                fileWriter.write(tModel.getValueAt(i,j).toString() + "\t");

            }

                fileWriter.write("\n");

            }

                fileWriter.close();

            }catch(Exception e){

                JOptionPane.showMessageDialog(null, e);

            }

        }

   }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(riwayattransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(riwayattransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(riwayattransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(riwayattransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new riwayattransaksi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton export;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton tampilkandata;
    private javax.swing.JTable tbl;
    // End of variables declaration//GEN-END:variables
private void open_db(){
    try{
        Class.forName("com.mysql.jdbc.Driver");
        koneksi=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/proyek", "root", "");
        st=(Statement)koneksi.createStatement();
    }catch(Exception a){
        JOptionPane.showMessageDialog(null, "Koneksi Gagal");
        System.out.println(a.getMessage());
        
    }

}
private void tampilkan_data() {
        
        DefaultTableModel tabeldealer = new DefaultTableModel();
        tabeldealer.addColumn("No");
        tabeldealer.addColumn("Nofaktur");
        tabeldealer.addColumn("Produk");
        tabeldealer.addColumn("Ukuran");
        tabeldealer.addColumn("Harga");
        tabeldealer.addColumn("Jumlah");
        tabeldealer.addColumn("Total");
        
        try {
            open_db();
             String sql = "select * from transaksi";
            st= (Statement) koneksi.createStatement();
            ResultSet rs=st.executeQuery(sql);
            while (rs.next()) {
                Object[] a =new Object[7];
                a[0] = rs.getString("id");
                a[1] = rs.getString("nofaktur");
                a[2] = rs.getString("produk");
                a[3] = rs.getString("ukuran");
                a[4] = rs.getString("harga");
                a[5] = rs.getString("jumlah_pesanan");
                a[6] = rs.getString("totalharga");
                
                tabeldealer.addRow(a);
                
            }
           tbl.setModel(tabeldealer);
        } catch (Exception e) {
        }
    }
}
